### ISSUE TITLE
Is this suitable for production?

### ISSUE THREAD

**Issue by microspace** [divio/django-cms-preview#23]
Is this docker image suitable for production?
do you provide official docker images?

**Comment by FinalAngel** [comment]
@microspace there is no official Docker image available yet. We recommend using the https://github.com/nephila/djangocms-installer and then creating your own image as everyone has their custom needs. You can also checkout https://github.com/divio/django-cms-demo

**Comment by microspace** [comment]
Thank you! I've found some other resources for deployment: 
https://medium.com/@JakubBorys/docerizing-django-cms-28c3ed11ba43
